# Generated by Django 6.0.6 on 2026-07-02 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='Slug')),
                ('emoji', models.CharField(blank=True, default='🍩', max_length=10, verbose_name='Emoji')),
                ('description', models.CharField(blank=True, default='', max_length=200, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Cobertura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Precio por dona')),
                ('emoji', models.CharField(blank=True, default='', max_length=10, verbose_name='Emoji')),
            ],
            options={
                'verbose_name': 'Cobertura',
                'verbose_name_plural': 'Coberturas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200, verbose_name='Nombre del cliente')),
                ('customer_phone', models.CharField(max_length=50, verbose_name='Teléfono')),
                ('items', models.JSONField(verbose_name='Productos')),
                ('total', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Total')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('completed', 'Completado')], default='pending', max_length=20, verbose_name='Estado')),
                ('notified', models.BooleanField(default=False, verbose_name='Notificado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='Slug')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Precio')),
                ('emoji', models.CharField(blank=True, default='', max_length=10, verbose_name='Emoji')),
                ('description', models.TextField(blank=True, default='', verbose_name='Descripción')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Imagen')),
                ('available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='trocitos.category', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['category__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CharolaConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.PositiveIntegerField(verbose_name='Cantidad de donas')),
                ('product', models.OneToOneField(limit_choices_to={'category': 'charolas'}, on_delete=django.db.models.deletion.CASCADE, related_name='charola_config', to='trocitos.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Configuración de charola',
                'verbose_name_plural': 'Configuraciones de charolas',
            },
        ),
    ]
